baseURL = 'https://www.praguevara.dev/'
languageCode = 'en-us'
title = "praguevara"
theme = "PaperMod"
defaultContentLanguage = "en"

[params]
author = "Pablo Ramón Guevara"
description = "praguevara's site"
keywords = ["blog", "developer", "personal"]
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true
ShowToc = true

[params.profileMode]
enabled = true
title = "Pablo Ramón Guevara"
subtitle = "Computer Engineer"
imageUrl = "images/avatar.webp"
imageTitle = "portrait"

[[params.socialIcons]]
name = "github"
url = "https://github.com/praguevara"

[[params.socialIcons]]
name = "x"
url = "https://x.com/praguevara"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/pablo-ram%C3%B3n-guevara-498283165/"

[menu]
[[menu.main]]
identifier = "posts"
name = "Blog"
url = "/posts/"
weight = 10

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 20

[[menu.main]]
identifier = "cv"
name = "CV"
url = "/cv/"
weight = 30

