baseURL = 'https://praguevara.dev/'
languageCode = 'en-us'
title = "praguevara"
theme = "hugo-coder"
defaultContentLanguage = "en"

[params]
author = "praguevara"
avatarURL = "images/avatar.jpg"
description = "praguevara's site"
keywords = "blog,developer,personal"

[[params.social]]
name = "GitHub"
icon = "fab fa-github fa-2x"
url = "https://github.com/praguevara"

[[params.social]]
name = "Twitter"
icon = "fab fa-x-twitter fa-2x"
url = "https://x.com/praguevara"

[[params.social]]
name = "LinkedIn"
icon = "fab fa-linkedin fa-2x"
url = "https://www.linkedin.com/in/pablo-ram%C3%B3n-guevara-498283165/"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "Blog"
weight = 1
url = "/posts"
